services:
  postgres:
    image: postgis/postgis:17-3.5-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=supersecretpassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      retries: 1
      start_interval: 5s
      start_period: 1s

  astro:
    image: astro-test
    ports:
      - "4321:4321"
    environment:
      - DATABASE_URL=postgresql://postgres:supersecretpassword@postgres:5432/postgres
    depends_on:
      postgres:
        condition: service_healthy

  scraper:
    image: scraper-test
    environment:
      - DATABASE_URL=postgresql://postgres:supersecretpassword@postgres:5432/postgres
    depends_on:
      postgres:
        condition: service_healthy
