name: build

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.frontend
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/gasolineras-frontend:latest
            ghcr.io/${{ github.actor }}/gasolineras-frontend:${{ github.sha }}

      - name: Build and push scraper
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.scraper
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/gasolineras-scraper:latest
            ghcr.io/${{ github.actor }}/gasolineras-scraper:${{ github.sha }}
